// Markdown renderer tests: vectors generated by kramdown (test/vectors.rb)

struct MdVector {
    std::string_view in;
    std::string_view want;
};

static MdVector mdvectors[] = {
#include "vectors.inc"
};

// Highlighting is not part of the vectors: drop spans inside code blocks.
static std::string unhighlight(std::string_view s)
{
    std::string b;
    b32 code = 0;
    for (iz i = 0; i < std::ssize(s);) {
        std::string_view rest = s.substr(i);
        if (rest.starts_with("<pre class=\"highlight\"><code>")) {
            code = 1;
        } else if (rest.starts_with("</code></pre>")) {
            code = 0;
        } else if (code && rest.starts_with("<span")) {
            for (; i<std::ssize(s) && s[i]!='>'; i++) {}
            i++;
            continue;
        } else if (code && rest.starts_with("</span>")) {
            i += 7;
            continue;
        }
        b += s[i++];
    }
    return b;
}

static void test_markdown(Test *t)
{
    for (iz i = 0; i < std::ssize(mdvectors); i++) {
        Log log = {};
        Markdown md = markdown(mdvectors[i].in, "vector", 1, &log);

        std::string name;
        name += "markdown vector ";
        name += std::to_string(i);
        name += ": ";
        name += mdvectors[i].in;
        expect(t, name, unhighlight(md.html), mdvectors[i].want);
    }

    // Excerpts end at a top-level <!--more-->, else at the first blank line
    Log log = {};
    Markdown md = markdown("A\nB\n\nC\n", "", 1, &log);
    expect(t, "excerpt blank", md.html.substr(0, md.excerpt), "<p>A\nB</p>\n");
    md = markdown("A\n\nB\n\n<!--more-->\n\nC\n", "", 1, &log);
    expect(t, "excerpt more", md.html.substr(0, md.excerpt), "<p>A</p>\n\n<p>B</p>\n\n");
    md = markdown("A\n", "", 1, &log);
    expect(t, "excerpt whole", md.html.substr(0, md.excerpt), "<p>A</p>\n");
    md = markdown("A `<!--more-->`\n\nB\n\n<!--more-->\n", "", 1, &log);
    expect(t, "excerpt code", md.html.substr(0, md.excerpt),
           "<p>A <code>&lt;!--more--&gt;</code></p>\n\n<p>B</p>\n\n");
    md = markdown("> A\n>\n> <!--more-->\n\nB\n", "", 1, &log);
    expect(t, "excerpt nested", md.html.substr(0, md.excerpt),
           "<blockquote>\n  <p>A</p>\n\n  <!--more-->\n</blockquote>\n");

    // Syntax that kramdown would parse differently is reported (these
    // were checked against kramdown)
    static struct { std::string_view in; std::string_view want; } warnings[] = {
        {"a | b\n",                "tables are not supported"},
        {"<b>x</b> | y\n",         "tables are not supported"},
        {"`|` and <kbd>|</kbd>\n", ""},
        {"a|b\nc\n",               ""},
        {"a\n: b\n",               "definition lists are not supported"},
        {"x\n\n: b\n",             "definition lists are not supported"},
        {"* x\n\n: b\n",           ""},
        {"$$x$$\n",                "math blocks are not supported"},
        {"$$|\n",                  "tables are not supported"},
        {"[^a]: b\n",              "footnotes are not supported"},
        {"[^]: b\n",               ""},
        {"<div><p markdown=\"1\">a</p></div>\n", "the markdown attribute is not supported"},
    };
    for (iz i = 0; i < std::ssize(warnings); i++) {
        Log log = {};
        markdown(warnings[i].in, "w", 1, &log);
        std::string_view got  = log.buf;
        std::string_view want = warnings[i].want;
        if (std::ssize(want) && got.contains(want)) {
            got = want;
        }
        std::string name;
        name += "markdown warning: ";
        name += warnings[i].in;
        expect(t, name, got, want);
    }

    // Deep nesting renders as text, bounding recursion
    log     = {};
    std::string deep;
    for (i32 i = 0; i < 2*MAXDEPTH; i++) {
        deep += "> <span>";
    }
    markdown(deep, "w", 1, &log);
    std::string_view got  = log.buf;
    std::string_view want = "pathological nesting";
    expect(t, "markdown deep nesting", got.contains(want) ? want : got, want);
}
